name: build

on:
  - push
  - pull_request

jobs:
  build:
    name: build
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: prepare
        run: |
          make prepare
      - name: build
        run: |
          make
      - name: upload
        uses: actions/upload-artifact@v4
        with:
          name: docs
          path: |
            dist/*.tar.gz
